-- TODO-App database schema reference
-- PostgreSQL-oriented documentation schema based on Django tasks.models.
-- Use Django migrations as the source of truth in the app.

CREATE TABLE tasks_tasklist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    session_key VARCHAR(80) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_task_list_name_per_session UNIQUE (session_key, name)
);

CREATE INDEX tasks_tasklist_session_key_idx
    ON tasks_tasklist (session_key);

CREATE TABLE tasks_recurrence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    frequency VARCHAR(12) NOT NULL,
    interval INTEGER NOT NULL DEFAULT 1 CHECK (interval >= 1),
    weekday_mask SMALLINT NULL CHECK (weekday_mask IS NULL OR weekday_mask BETWEEN 1 AND 127),
    day_of_month SMALLINT NULL CHECK (day_of_month IS NULL OR day_of_month BETWEEN 1 AND 31),
    end_date DATE NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT recurrence_frequency_valid CHECK (frequency IN ('daily', 'weekly', 'monthly'))
);

CREATE INDEX tasks_recurrence_created_at_idx
    ON tasks_recurrence (created_at DESC);

CREATE TABLE tasks_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_list_id BIGINT NOT NULL REFERENCES tasks_tasklist(id) ON DELETE CASCADE,
    parent_id BIGINT NULL REFERENCES tasks_task(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    notes TEXT NOT NULL DEFAULT '',
    due_date TIMESTAMPTZ NULL,
    status VARCHAR(8) NOT NULL DEFAULT 'open',
    priority VARCHAR(8) NOT NULL DEFAULT 'medium',
    "order" INTEGER NOT NULL DEFAULT 0 CHECK ("order" >= 0),
    recurrence_id BIGINT NULL REFERENCES tasks_recurrence(id) ON DELETE SET NULL,
    spawned_from_id BIGINT NULL REFERENCES tasks_task(id) ON DELETE SET NULL,
    completed_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ NULL,
    CONSTRAINT task_status_valid CHECK (status IN ('open', 'done')),
    CONSTRAINT task_priority_valid CHECK (priority IN ('low', 'medium', 'high'))
);

CREATE INDEX tasks_task_task_list_id_idx
    ON tasks_task (task_list_id);

CREATE INDEX tasks_task_parent_id_idx
    ON tasks_task (parent_id);

CREATE INDEX tasks_task_status_idx
    ON tasks_task (status);

CREATE INDEX tasks_task_due_date_idx
    ON tasks_task (due_date);

CREATE INDEX tasks_task_deleted_at_idx
    ON tasks_task (deleted_at);

CREATE INDEX tasks_task_list_parent_order_idx
    ON tasks_task (task_list_id, parent_id, "order");

CREATE TABLE tasks_taskevent (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NULL REFERENCES tasks_task(id) ON DELETE SET NULL,
    task_list_id BIGINT NULL REFERENCES tasks_tasklist(id) ON DELETE SET NULL,
    session_key VARCHAR(80) NOT NULL,
    action VARCHAR(20) NOT NULL,
    changes JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT task_event_action_valid CHECK (
        action IN (
            'created',
            'updated',
            'completed',
            'reopened',
            'soft_deleted',
            'restored',
            'reordered',
            'spawned'
        )
    )
);

CREATE INDEX tasks_taskevent_session_key_idx
    ON tasks_taskevent (session_key);

CREATE INDEX tasks_taskevent_created_at_idx
    ON tasks_taskevent (created_at DESC);

CREATE INDEX tasks_taskevent_task_id_idx
    ON tasks_taskevent (task_id);

CREATE INDEX tasks_taskevent_task_list_id_idx
    ON tasks_taskevent (task_list_id);
